require:
  - rubocop-performance
#  - rubocop_lineup

AllCops:
  TargetRubyVersion: 2.5
  NewCops: disable

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
    - module_inclusion
    - constants
    - public_class_methods
    - initializer
    - public_methods
    - protected_methods
    - private_methods

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Enabled: true
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes: http, https

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics:
  Enabled: true

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
  ExcludedMethods: ['included', 'namespace']

Metrics/ClassLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 15

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WhenThen:
  Enabled: true

Style/WordArray:
  Enabled: false
